### ISSUE TITLE
not an error just asking

### ISSUE THREAD

**Issue by Ravan1190** [dj-yacine-flutter/brain_fusion#12]
bro why did you removed nsfw generates ? 
its shows flowers. When i write nsfw prompt

please bring it back. :(

**Comment by dj-yacine-flutter** [comment]
> bro why did you removed nsfw generates ? its shows flowers. When i write nsfw prompt
> 
> please bring it back. :(

Hi ,
Thank you for reaching out and sharing your feedback regarding the removal of the NSFW generates feature. I appreciate your input and understand your concern.

The decision to remove the NSFW feature was made in order to align the package with certain guidelines and policies, and to ensure a wider range of appropriate use cases for our users. However, I understand that this feature may be important to some users.

While I am unable to directly add the NSFW generates feature back into the package, I encourage you to explore customizations or extensions that can be implemented on top of the existing package to meet your specific requirements. This will allow you to tailor the functionality according to your needs while maintaining the core package's guidelines.

If you need any assistance or have any further questions, please feel free to reach out. I'm here to help.

I m the package creator not the server side
 
Thank you once again for your feedback.

Best regards,
dj-yacine

**Comment by Ravan1190** [comment]
So, now we can't generate nsfw, right?
